import {chromium} from '@playwright/test';
import {mkdir, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('.', import.meta.url));
const browser = await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})});
const page = await browser.newPage({viewport:{width:1366,height:768}});
page.setDefaultTimeout(10000);
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', m => {if(m.type()==='error')errors.push(m.text());});
await mkdir(`${root}screenshots`,{recursive:true});
const shot = name => page.screenshot({path:`${root}screenshots/lowest-${name}.png`,fullPage:true});
const cleanUI = async () => {
  assert.doesNotMatch(await page.locator('body').innerText(),/signal|Highest|Watch AI|How to play/i);
  assert.equal(await page.locator('[data-signal], [data-action="signal"], .signal').count(),0);
  const shadows=await page.evaluate(()=>[...document.querySelectorAll('*')].filter(el=>{const s=getComputedStyle(el);return s.boxShadow!=='none'||s.textShadow!=='none'||s.filter.includes('drop-shadow');}).map(el=>el.className));
  assert.deepEqual(shadows,[],'No shadows anywhere');
};
await page.goto('http://localhost:4173/?seed=1');
assert.equal(await page.locator('.hand-cards .card').count(),5);
assert.equal(await page.getByText('Waiting for call',{exact:true}).count(),5);
await cleanUI();await shot('01-deal');
await page.getByRole('button',{name:'Call DATA',exact:true}).click();
assert.equal(await page.locator('.hand-cards button:enabled').count(),2);
await shot('02-play');
await page.getByRole('button',{name:'Play DATA 1, Human report',exact:true}).click();
await page.locator('[data-action="install"]').waitFor();
assert.equal(await page.locator('.players').getByText('Discard',{exact:true}).count(),4);
await cleanUI();await shot('03-trick');
let installs=0;
const started=Date.now();
while(!await page.locator('[data-action="replay"]').count()) {
  if(Date.now()-started>40000)throw Error('Game stalled');
  if(await page.locator('[data-action="install"]').count()) {
    const called=(await page.locator('.prompt small').innerText()).replace('Called: ','');
    const played=await page.locator('.players .card').evaluateAll(cards=>cards.map(card=>({suit:card.querySelector('.card-suit').textContent,rank:Number(card.querySelector('.card-rank').textContent),winner:card.classList.contains('winner')})));
    const relevant=played.filter(c=>c.suit===called);
    const win=played.find(c=>c.winner);
    assert.equal(win.suit,called);
    assert.equal(win.rank,Math.min(...relevant.map(c=>c.rank)),'Only lowest called-suit card wins');
    await page.locator('[data-action="install"]').click();installs++;
  }
  else if(await page.locator('[data-call]:enabled').count())await page.locator('[data-call]:enabled').first().click();
  else if(await page.locator('[data-action="bot-call"]').count())await page.locator('[data-action="bot-call"]').click();
  else if(await page.locator('.hand-cards button:enabled').count())await page.locator('.hand-cards button:enabled').first().click();
  else await page.waitForTimeout(100);
}
assert.equal(installs,5);assert.equal(await page.locator('.built').count(),5);
const result=await page.locator('.total').innerText();
const sum=await page.locator('.built strong').evaluateAll(els=>els.reduce((s,el)=>s+Number(el.textContent),0));
assert.equal(result,`COST ${sum}`);
await cleanUI();await shot('04-complete');
await page.locator('[data-action="replay"]').click();
assert.equal(await page.locator('.hand-cards .card').count(),5);
const bounds=await page.locator('.hand-cards').evaluate(el=>({bottom:el.getBoundingClientRect().bottom,viewport:innerHeight}));
assert.ok(bounds.bottom<=bounds.viewport,'Full hand fits projector');
await page.getByRole('button',{name:'Call DATA',exact:true}).click();
await page.getByRole('button',{name:'Play DATA 1, Human report',exact:true}).click();
await page.locator('[data-action="reset"]').click();await page.waitForTimeout(800);
assert.equal(await page.locator('.hand-cards .card').count(),5);assert.equal(await page.locator('.players .card').count(),0);
await page.goto('http://localhost:4173/?seed=175');
await page.getByRole('button',{name:'Call VERIFICATION',exact:true}).click();
assert.equal(await page.locator('.hand-cards button:enabled').count(),5);
await page.locator('.hand-cards button:enabled').first().click();
await page.locator('[data-action="install"]').waitFor();await page.locator('[data-action="install"]').click();
assert.equal(await page.locator('.total').innerText(),'COST -');assert.equal(await page.locator('.controls strong').innerText(),'Ship incomplete');
await cleanUI();await shot('05-incomplete');
await page.goto('http://localhost:4173/?seed=1');await page.setViewportSize({width:390,height:844});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow');await shot('06-mobile');
assert.deepEqual(errors,[]);
await writeFile(`${root}reports/browser-lowest-qa.json`,JSON.stringify({checkedAt:new Date().toISOString(),result,bounds,errors,checks:['no signal UI','no box/text/filter shadows','lowest called-suit winner verified every round','off-suit cards discarded','complete five-round human game','legal follow suit','reset cancels timers','same-deal replay','projector fit','no score for incomplete deal','mobile no page overflow']},null,2)+'\n');
console.log('Lowest-wins browser QA passed',result,bounds);await browser.close();
