import {chromium} from '@playwright/test';
import {mkdir, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const root = fileURLToPath(new URL('.', import.meta.url));
const browser = await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})});
const page = await browser.newPage({viewport:{width:1366,height:768}});
page.setDefaultTimeout(10000);
const errors = [];
page.on('pageerror', e => errors.push(String(e)));
page.on('console', m => {if(m.type()==='error')errors.push(m.text());});
await mkdir(`${root}screenshots`,{recursive:true});
const shot = name => page.screenshot({path:`${root}screenshots/ascii-${name}.png`,fullPage:true});
const asciiOnly = async () => assert.ok(!/[^\x00-\x7f]/.test(await page.locator('body').innerText()),'Only ASCII text');
await page.goto('http://localhost:4173/?seed=1');
assert.equal(await page.locator('.hand-cards .card').count(),5);
assert.equal(await page.locator('.card-back, svg, img, canvas').count(),0);
assert.equal(await page.getByText('Waiting for call',{exact:false}).count(),5);
assert.doesNotMatch(await page.locator('body').innerText(),/Watch AI|How to play|ONE CREW|HIGHEST|ONLY/);
await asciiOnly(); await shot('01-deal');
await page.locator('[data-action="signal"]').click();
assert.equal(await page.locator('.hand-cards button:enabled').count(),3);
await shot('02-signal');
await page.getByRole('button',{name:'Signal DATA 1, Human report',exact:true}).click();
assert.match(await page.locator('.seat').last().innerText(),/Signal: DATA 1/);
assert.equal(await page.locator('[data-action="signal"]').count(),0);
await page.getByRole('button',{name:'Call DATA',exact:true}).click();
assert.equal(await page.locator('.hand-cards button:enabled').count(),2);
await shot('03-play');
await page.getByRole('button',{name:'Play DATA 1, Human report',exact:true}).click();
await page.locator('[data-action="install"]').waitFor();
assert.equal(await page.locator('.players').getByText('Discard',{exact:false}).count(),4);
await asciiOnly(); await shot('04-trick');
let installs = 0;
const started = Date.now();
while(!await page.locator('[data-action="replay"]').count()) {
  if(Date.now()-started>40000)throw Error('Game stalled');
  if(await page.locator('[data-action="install"]').count()){await page.locator('[data-action="install"]').click();installs++;}
  else if(await page.locator('[data-call]').count())await page.locator('[data-call]').first().click();
  else if(await page.locator('[data-action="bot-call"]').count())await page.locator('[data-action="bot-call"]').click();
  else if(await page.locator('.hand-cards button:enabled').count())await page.locator('.hand-cards button:enabled').first().click();
  else await page.waitForTimeout(100);
}
assert.equal(installs,5);
assert.equal(await page.locator('.built').count(),5);
const result = await page.locator('.total').innerText();
assert.equal(result,'Total: 16');
await asciiOnly(); await shot('05-complete');
await page.locator('[data-action="replay"]').click();
assert.equal(await page.locator('.hand-cards .card').count(),5);
const bounds=await page.locator('.hand-cards').evaluate(el=>({bottom:el.getBoundingClientRect().bottom,viewport:innerHeight}));
assert.ok(bounds.bottom<=bounds.viewport,'All five cards fit projector');
await page.locator('[data-action="signal"]').click();
assert.ok(await page.locator('.hand-cards').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight),'Signal mode fits projector');
await page.locator('[data-action="cancel"]').click();
await page.getByRole('button',{name:'Call DATA',exact:true}).click();
await page.getByRole('button',{name:'Play DATA 1, Human report',exact:true}).click();
await page.locator('[data-action="reset"]').click();
await page.waitForTimeout(800);
assert.equal(await page.locator('.hand-cards .card').count(),5);
assert.equal(await page.locator('.players .card').count(),0);
await page.goto('http://localhost:4173/?seed=175');
await page.getByRole('button',{name:'Call VERIFICATION',exact:true}).click();
assert.equal(await page.locator('.hand-cards button:enabled').count(),5);
await page.locator('.hand-cards button:enabled').first().click();
await page.locator('[data-action="install"]').waitFor();await page.locator('[data-action="install"]').click();
assert.equal(await page.locator('.total').innerText(),'Total: -');
assert.equal(await page.locator('.controls span').innerText(),'Incomplete');
await asciiOnly();await shot('06-incomplete');
await page.goto('http://localhost:4173/?seed=1');
await page.setViewportSize({width:390,height:844});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow');
await shot('07-mobile');
assert.deepEqual(errors,[]);
await writeFile(`${root}reports/browser-ascii-qa.json`,JSON.stringify({checkedAt:new Date().toISOString(),result,bounds,errors,checks:['ASCII-only rendered text','no artwork or hidden hands','one lowest signal','single-click legal play','complete five-round human game','reset cancels timers','same-deal replay','projector hand and signal mode fit','incomplete deal has no score','mobile no page overflow']},null,2)+'\n');
console.log('ASCII browser QA passed',result,bounds);
await browser.close();
